debug: true
server:
  port:
    8082
  servlet:
    context-path: /storeflexservice
 
spring:
########Data source ##############            
  datasource:
    url: jdbc:postgresql://storeflex.cdnznk1rek3c.ap-south-1.rds.amazonaws.com:5432/storeFlexDevDB
    username: StoreFDev
    password: StoreTech2022
  
  jpa:
   properties:
    show-sql: true
    hibernate:
     jdbc:
      lob:
       non_contextual_creation: true
     dialect: org.hibernate.dialect.PostgreSQLDialect
     naming:
           implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
     ddl-auto: none
     default_schema: storeflex_data
  #######file size for upload############
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB
      

testuser:
   username: storeflextest
   password: storeflex#123 