debug: true
server:
  port:
    8082
  servlet:
    context-path: /storeflexservice
###cloud credentail to access storeflex AWS##### 
cloud:
  aws:
   region:
    static:
    auto: false
   credentails:
    access-key: AKIATI22Z2T642TJIFMD
    secret-key: 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
    
### DB details in cloud #########
postgres:
 driver: org.postgresql.Driver
 db: jdbc
 dbname: storeFlexDevDB

### AWS postgres secret manager details ######### 
storeflexaws:
 dbsecret:
  name: dev/storeflexDB
  region: ap-south-1
  
spring:

  ##### GMAIL SMTP SERVER####  
  mail:
   host: smtp.gmail.com
   port: 587
   username: storeflexsl@gmail.com
   password: jgqzygjfoalyzzbj
   properties:
    mail:
     smtp:
      auth: true
      connectiontimeout: 5000
      timeout: 5000
      writetimeout: 5000
     starttls:
      enable: true
 ########Data source ##############         
  #datasource:
    #driver: jdbc:postgresql://storeflex.cdnznk1rek3c.ap-south-1.rds.amazonaws.com:5432/storeFlexDevDB
    #username: StoreFDev
    #password: StoreTech2022
  
  jpa:
   properties:
    show-sql: true
    hibernate:
     jdbc:
      lob:
       non_contextual_creation: true
     dialect: org.hibernate.dialect.PostgreSQLDialect
     naming:
           implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
     ddl-auto: none
     default_schema: storeflex_data
  #######file size for upload############
  servlet:
    multipart:
      max-file-size: 5000KB
      max-request-size: 5000KB

####TESTING PURPOSE#####################
testuser:
   username_temp: storeflextest
   password_temp: storeflex#123
   username_SL: storeflextest_SL
   password_SL: storeflex#123
   username_CL: storeflextest_CL
   password_CL: storeflex#123 
   username_CU: storeflextest_CU
   password_CU: storeflex#123

####StoreFlex ZOHO details ###########
signing:
  zoho:
    clientID: 1000.928LQ0H22FF73LRFU7KMF2TXSLPB6Y
    clientSecret: 19f3573ac7cdf167b54450485f72f8538a5c5a91d6
    refreshToken: 1000.e2bec535f208502a142d2eb8cdf959e1.18ce2a1018a9f30ab3fdf8d86389c9ee  

#JWT TOKEN    
jwt:
 secret: javainuse
 get:
  token:
   uri:/authenticate

